config/routes.rb
BugTracker::Application.routes.draw do

  match "/" => "main#index"

  resources :projects do
    resources :bugs, except: [:index, :delete]
  end

end

app/models/bug.rb
class Bug < ActiveRecord::Base
  attr_accessible :description, :title, :bug_status_id, :status

  belongs_to :project
  belongs_to :status, class_name: "BugStatus", foreign_key: :bug_status_id

  validates :title, presence: true
  validates :description, presence: true
  validates :bug_status_id, inclusion: { in: BugStatus::ALL_STATUSES.keys }
end

app/models/bug_status.rb
class BugStatus < ActiveRecord::Base
  attr_accessible :description
  has_many :bugs

  NEW = 1
  IN_PROGRESS = 2
  RESOLVED = 3
  CLOSED = 4
  REJECTED = 5

  ALL_STATUSES = {
    NEW => "New",
    IN_PROGRESS => "In progress",
    RESOLVED => "Resolved",
    CLOSED => "Closed",
    REJECTED => "Rejected"
  }
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :title, :description
  has_many :bugs

  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  before_filter :load_project

  def show
    @bug = @project.bugs.find(params[:id])
  end

  def new
    @bug = @project.bugs.build
    @bug.status = BugStatus.find(BugStatus::NEW)
  end

  def edit
    @bug = @project.bugs.find(params[:id])
  end

  def create
    @bug = @project.bugs.build(params[:bug])

    if @bug.save
      redirect_to project_bug_path(@project, @bug) , notice: 'Bug was successfully created.'
    else
      render action: "new"
    end
  end

  def update
    @bug = @project.bugs.find(params[:id])

    if @bug.update_attributes(params[:bug])
      redirect_to project_bug_path(@project, @bug), notice: 'Bug was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @bug = @project.bugs.find(params[:id])
    @bug.destroy
    redirect_to project_path(@project)
  end

  protected

  def load_project
    @project = Project.find(params[:project_id])
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    redirect_to projects_path
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @bugs = @project.bugs.includes(:status).all
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(params[:project])

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
       render action: "new"
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(params[:project])
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
  def bug_status_select_options
    BugStatus.all.map { |status| [status.description, status.id] }
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/bugs/_form.html.erb
<%= form_for(@bug, url: url) do |f| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :bug_status_id %><br />
    <%= f.select :bug_status_id, bug_status_select_options %>
  </div>
  <div class="actions">
    <%= f.submit %><%= link_to "cancel", project_path(@project), class: "cancel" %>
  </div>
<% end %>

app/views/bugs/edit.html.erb
<h1><%= @project.title %></h1>

<h2>Editing bug</h2>

<%= render partial: 'form', locals: { url: project_bug_path(@project, @bug) } %>

app/views/bugs/index.html.erb
<h1>Listing bugs</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bugs.each do |bug| %>
  <tr>
    <td><%= bug.title %></td>
    <td><%= bug.description %></td>
    <td><%= link_to 'Show', bug %></td>
    <td><%= link_to 'Edit', edit_bug_path(bug) %></td>
    <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bug', new_bug_path %>

app/views/bugs/new.html.erb
<h1><%= @project.title %></h1>

<h2>Create a new bug</h2>

<%= render partial: 'form', locals: { url: project_bugs_path(@project) } %>

app/views/bugs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="title-with-controls">
  <h1><%= @project.title %> - Bug ID: <%= @bug.id %></h1>

  <div id="page-controls">
    <%= link_to 'Edit this bug', edit_project_bug_path(@project, @bug) %>
  </div>
</div>


<div class="field-list">
  <div class="field">
    <div class="field-name">Title:</div>
    <div><%= @bug.title %></div>
  </div>

  <div class="field">
    <div class="field-name">Description:</div>
    <div><%= @bug.description %></div>
  </div>

  <div class="field">
    <div class="field-name">Status:</div>
    <div><%= @bug.status.description %></div>
  </div>
</div>

<%= link_to "<< Back to project", project_path(@project) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BugTracker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <% if Rails.env.development? %>
    <%= javascript_include_tag "vendor/live_css" %>
  <% end %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="page-header">
  <h1>Bug Tracker</h1>
</div>

<div id="page-content" class="page-content-wrapper">
  <%= yield %>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %><%= link_to "cancel", cancel_path, class: "cancel" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1><%= @project.title %></h1>

<%= render partial: 'form', locals: { cancel_path: project_path(@project) } %>

app/views/projects/index.html.erb
<div class="title-with-controls">
  <h1>Projects</h1>

  <div id="page-controls">
    <%= link_to 'Create a new Project', new_project_path %>
  </div>
</div>

<p class="small">
<% if @projects.count.eql? 0 %>
  We aren't tracking any projects yet. <%= link_to "Create a new project", new_project_path %>
  to get started.
<% else %>
  We're currently tracking bugs for <%= pluralize(@projects.count, "project") %>:
<% end %>
</p>

<ul class="project-list">
  <% @projects.each do |project| %>
    <li><strong><%= link_to project.title, project_path(project) %></strong>: <%= project.description %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render partial: 'form', locals: { cancel_path: projects_path } %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="title-with-controls">
  <h1><%= @project.title %> - Bug List</h1>

  <div id="page-controls">
    <%= link_to "New bug", new_project_bug_path(@project) %> |
    <%= link_to 'Edit Project', edit_project_path(@project) %>
  </div>
</div>

<% if @bugs.empty? %>
  <p class="small">
  No bugs have been filed.
  <%= link_to "Click here to file one", new_project_bug_path(@project) %>
  </p>
<% else %>
  <p class="small">
  We are currently tracking <%= pluralize(@bugs.count, "bug") %>:
  </p>
  <table class="styled">
    <thead>
      <tr>
        <th class="center">#</th>
        <th>Title</th>
        <th class="center">Status</th>
        <th>Created on</th>
      </tr>
    </thead>
    <tbody>
      <% @project.bugs.includes(:status).each do |bug| %>
        <tr>
          <td class="center"><%= link_to bug.id, project_bug_path(@project, bug) %></td>
          <td><%= bug.title %></td>
          <td class="center"><%= bug.status.description %></td>
          <td><%= bug.created_at %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<% end %>

<%= link_to "<< Return to projects", projects_path, class: "small" %>